### ISSUE TITLE
calling cob-start manually after cob-stop does not work

### ISSUE THREAD

**Issue by MattiaRacca** [ipa320/setup_cob4#102]
investigated together with @ipa-fmw. We saw this on cob4-5 and cob4-8.

´sudo cob-stop´ killed roscore

´sudo cob-start´ throws an error

´´´
--- cob4-8-h1 ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 0.317/0.317/0.317/0.000 ms
cob4-8-h1 alive
File exists
File exists
File exists
test: robot.launch: Using workspace setup file /etc/ros/indigo/cob.d/setup/setup.sh
test: Provided the following robot:=cob4-8
test: robot.launch: Launching on interface eth0, ROS_IP=10.4.8.11, ROS_MASTER_URI=http://10.4.8.11:11311
test: robot.launch: Generated launchfile: /tmp/robot.launch.launch
test: robot.launch: Started roslaunch as background process, PID 31378
WARNING: cannot create log directory [/tmp/e510fe2a-5110-11e7-8596-f44d3066217f]. Please set ROS_LOG_DIR to a writable location.
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

deprecated: xacro tags should be prepended with 'xacro' xml namespace.
Use the following script to fix incorrect usage:
        find . -iname "*.xacro" | xargs sed -i 's#<\([/]\?\)\(if\|unless\|include\|arg\|property\|macro\|insert_block\)#<\1xacro:\2#g'
when processing file: /opt/ros/indigo/share/schunk_description/urdf/lwa4p_extended/lwa4p_extended.urdf.xacro
included from: /u/robot/git/care-o-bot/install/share/cob_hardware_config/robots/cob4-8/urdf/cob4-8.urdf.xacro

started roslaunch server http://10.4.8.11:46469/
remote[cob4-8-t2-0] starting roslaunch
remote[cob4-8-t2-0]: creating ssh connection to cob4-8-t2:22
/usr/lib/python2.7/dist-packages/Crypto/Cipher/blockalgo.py:141: FutureWarning: CTR mode needs counter parameter, not IV
  self._cipher = factory.new(key, *args, **kwargs)
No handlers could be found for logger "roslaunch.remoteprocess"
remote[cob4-8-t2-0]: failed to launch on cob4-8-t2:

Unable to establish ssh connection to [cob4-8-t2:22]: No authentication methods available

[cob4-8-t2-0] killing on exit
unable to start remote roslaunch child: cob4-8-t2-0
The traceback for the exception was written to the log file
´´´

**Comment by ipa-nhg** [comment]
This is an issue with robot_upstart, cob-start can only be used as upstart job.

To use a general cob-start command please switch to the new upstart version https://github.com/ipa320/setup_cob4/pull/96

**Comment by ipa-fmw** [comment]
this is fixed in #105
