### ISSUE TITLE
extend ddwrt docu

### ISSUE THREAD

**Issue by ipa-fmw** [ipa320/setup_cob4#116]
in https://github.com/ipa320/setup_cob4/blob/master/manual_administrator/README_ddwrt.md
docu
- [x] activate SSH deamon after flashing with ddwrt
- [x] apt-get install sshpass
- [x] accept ssh key in script

script
- [x] reading of certificates not working

**Comment by ipa-fxm** [comment]
@ipa-fmw @ipa-bnm 
solved in #115?
can we close this?

**Comment by ipa-fmw** [comment]
we can close as soon as #115 is merged (should close automatically)

fixed in #115

**Comment by ipa-fxm** [comment]
fixed in #115
