### ISSUE TITLE
remove VM stuff from setup/upstart

### ISSUE THREAD

**Issue by ipa-fxm** [ipa320/setup_cob4#119]
as a final consequence of https://github.com/ipa320/msh/issues/714

do this once ipa320/msh#811 is merged

**Comment by ipa-fxm** [comment]
@ipa-fmw @ipa-nhg @ipa-bnm 
has this been done during your efforts regarding the image setup?

**Comment by ipa-nhg** [comment]
This has nothing to do with the installation images.
Done by https://github.com/ipa320/setup_cob4/pull/147/files.
