### ISSUE TITLE
rework default user bashrc and rosinstall file

### ISSUE THREAD

**Issue by ipa-fxm** [ipa320/setup_cob4#122]
in order to reflect workspace chaining as discussed with @ipa-bnm @ipa-fmw

**Comment by ipa-fmw** [comment]
we'll setup for research and development robots
- ```/u/robot/git/care-o-bot``` with devel space and all bringup repositories chaining ```/opt/ros```
- ```/u/USER/git/care-o-bot``` with an empty workspace chaining ```/u/robot/git/care-o-bot/devel```

we'll setup for robots in operation
- ```/u/robot/git/care-o-bot``` with devel space and all bringup repositories chaining ```/opt/ros```
- ```/u/LIVEUSER/git/cob``` with all bringup repositories chaining ```/u/robot/git/```
- ```/u/LIVEUSER/git/nav``` with all navigation repositories chaining ```/u/LIVEUSER/git/cob```
- ```/u/LIVEUSER/git/APPLICATION``` with all demo repositories chaining ```/u/LIVEUSER/git/nav```
- ```/u/LIVEUSER/git/care-o-bot``` with an empty workspace chaining ```/u/LIVEUSER/git/APPLICATION```
So for live operations we'll not use the robot account any longer but have everything on the LIVEUSER account.

**Comment by ipa-fxm** [comment]
we'll add rosinstall files for each sub-workspace to unity-robotics/msh

**Comment by ipa-fmw** [comment]
done on cob4-12 and works. rosinstall files see https://github.com/unity-robotics/msh/pull/14
