### ISSUE TITLE
[cob-adduser] check if we can use robot instead of root account

### ISSUE THREAD

**Issue by ipa-fmw** [ipa320/setup_cob4#123]

**Comment by ipa-nhg** [comment]
it is not possible, at least once cob-adduser has to be called with the root user because the robot user does not exist for the slaves

**Comment by ipa-fmw** [comment]
ok, then we need a post-install script to generate a ssh-key for the root account on b1 and then ssh-copy-id to all other pcs.

**Comment by ipa-nhg** [comment]
issue solved using the post_install script and the argument PubkeyAuthentification=no, see: https://github.com/ipa320/setup_cob4/pull/135
