### ISSUE TITLE
[setup from image] status report

### ISSUE THREAD

**Issue by ipa-fmw** [ipa320/setup_cob4#124]
created images from ipa-nhg/ReviewInstall from 27.7.17 3pm.

tests status for MASTER:
pc setup
- [x] network setup
- [x] grub
- [x] user accounts (robot and robot-local)
  - [x] ssh keys --> post install script
  - [x] sudo rights
  - [x] bashrc setup --> post install script
  - [x] bashrc setup /etc/cob.bash
- [x] catkin workspace for robot --> post install script
- [x] rosdep init & update --> post install script
- [x] udev rules in /etc/init.d and /etc/udev/rules.d
- [x] chrony setup
- [x] NFS setup
- [ ] touch screen adapt resolution --> manually
- [x] cob-shutdown
- [x] netdata
- [x] nomachine
- [x] install apt-cacher-ng

robot components
- [x] base driver
- [x] flexisoft
- [x] laser scanner (front, left, right) --> need serial numbers in /etc/init.d/udev_cob.sh --> post install script
- [x] light base
- [x] joystick
- [x] BMS

tests status for SLAVE:
pc setup
- [x] network setup
- [x] grub
- [x] bashrc setup /etc/cob.bash
- [x] user accounts --> post install script
- [x] rosdep init --> post install script
- [x] udev rules in /etc/udev/rules.d
- [x] chrony setup
- [x] NFS setup
- [x] netdata
- [x] nomachine
- [x] use apt-cacher proxy from -b1

robot components
- [x] torso/head/sensorring driver
- [ ] bluetooth setup hands --> manually 
- [x] h1: sound/mic
- [ ] h1: touch screen
- [x] h1: mimic

**Comment by ipa-nhg** [comment]
Updated the list with according to https://github.com/ipa320/setup_cob4/pull/131#pullrequestreview-55815472 and https://github.com/ipa320/setup_cob4/pull/131#pullrequestreview-55815472

**Comment by ipa-bnm** [comment]
nfs is not working because `nfs-kernel-server` and `autofs` are missing on the slave machines

**Comment by ipa-bnm** [comment]
tmux is missing

**Comment by ipa-nhg-dd** [comment]
nfs-kernel-server and autofs and tmux are added to slave configuration file.

**Comment by ipa-bnm** [comment]
`python-wstool` is missing

**Comment by ipa-bnm** [comment]
`python-pip` is missing

**Comment by ipa-nhg** [comment]
lets also add the python-catkin-tools to the images.

@ipa-nhg-dd could you please add for master and slave the packages:

python-wstool
python-pip
python-catkin-tools 

and please send a pull request with all the changes

**Comment by ipa-nhg-dd** [comment]
python-wstool
python-pip
python-catkin-tools
I have added the above packages in master and slave configuration files and tested.
@ipa-nhg I have included these packages along with ROS packages in the ROS installation module in configuration files of master and slave.

**Comment by ipa-fmw** [comment]
good copy-paste example https://www.debian.org/releases/squeeze/example-preseed.txt

**Comment by ipa-fmw** [comment]
I'll close this as we more or less successfully setup a whole robot (cob4-12) with the images
