### ISSUE TITLE
use apt-cacher-ng for robot pcs

### ISSUE THREAD

**Issue by ipa-fmw** [ipa320/setup_cob4#13]
* use apt-cacher-ng

install apt-cacher-ng on b1:
sudo apt-get install apt-cacher-ng

setup proxy on all pcs:
sudo vim /etc/apt/apt.conf.d/01proxy
and add
"
Acquire::http { Proxy "http://cob4-2-b1:3142"; };
"

* add to install instructions in manual and install script

**Comment by ipa-fmw** [comment]
is already configured on cob4-2. @ipa-nhg still needs to be added to install instructions in manual and install script

**Comment by ipa-nhg** [comment]
https://github.com/ipa320/setup_cob4/commit/f50054f4846f87a06e32c7351aad429bbcf8f2be
