### ISSUE TITLE
[cob-addusers] add .tmux.conf to the users home directories

### ISSUE THREAD

**Issue by ipa-bnm** [ipa320/setup_cob4#142]
please add the file `.tmux.conf` with the following entries to the users home directory.

```
set -g mode-mouse on
set -g history-limit 10000
```

this adds scrolling capability to tmux

**Comment by ipa-fez** [comment]
You can already scroll with  `<prefix>+Page Up`.

Also here's a minimal tmux.conf: https://github.com/ipa-fez/tipsntricks/blob/master/configs/tmux.conf

**Comment by ipa-fmw** [comment]
fixed in https://github.com/ipa320/setup_cob4/pull/177
