### ISSUE TITLE
[PostInstall/upstart] upstart_install.sh not working anymore

### ISSUE THREAD

**Issue by ipa-fmw** [ipa320/setup_cob4#149]
we're missing to replace variables (pc_list) in cob-start.

only post install script can be used but does not use upstart_install. we should call upstart_install from within the post install script.

**Comment by ipa-fmw** [comment]
@ipa-nhg: what's the purpose of having ```InstallUpstart``` and ```UpdateUpstart``` separated in the post install script? install upstart should just be callable multiple times so there's no need to do update upstart explicitly.

**Comment by ipa-nhg** [comment]
see: https://github.com/ipa320/setup_cob4/pull/147/files 
InstallUpstart copy all the needed files and change the rights of the usrrs and call UpdateUpstart where the upstart job is configured. The function UpdateUpstart can be called  for example to define new launch files that have  to be started, this is useful for demos or tests. We discussed and decided this together around 2 months ago...

**Comment by ipa-fmw** [comment]
fixed in #150
