### ISSUE TITLE
create sync_apt.sh script

### ISSUE THREAD

**Issue by ipa-fmw** [ipa320/setup_cob4#16]
normally we have the cob-ps-install.sh script for installing apt packages on the robot pcs.

due to manual installation it sometimes happens that there are other packages installed on the base pc than on others. This is hard to synchronize manually, so we should have a script that checks for all installed packages and triggers an `apt-get install` on all other pcs.

**Comment by ipa-fxm** [comment]
this is still an issue...any solution yet?

**Comment by ipa-nhg** [comment]
still not found any proper solution...

**Comment by ipa-nhg** [comment]
Done https://github.com/ipa320/setup_cob4/pull/49

**Comment by ipa-fxm** [comment]
done in #51

**Comment by ipa-nhg** [comment]
I would like to keep this issue still open, we should also check the version of the installed packages... but the #51 can be merged, it is useful and a good start point

**Comment by ipa-fmw** [comment]
I think checking the version is not needed in first place and can even produce errors if there is different hardware attached to the pcs. without version it should always install the newest version on the apt-server. 

worked well today on cob4-paul-ingolstadt, so I'll close this
