### ISSUE TITLE
[images] enhancements for images setup

### ISSUE THREAD

**Issue by floweisshardt** [ipa320/setup_cob4#170]
- [ ] clone setup repository on robot account: ```git clone https://github.com/ipa320/setup_cob4```
- [x] candump is missing: `sudo apt-get install can-utils` (see https://github.com/ipa320/setup_cob4/pull/175)
- [x] disable update popup https://github.com/ipa320/msh/issues/872
- [x] enable passthrough filter in apt-cacher-ng for git-lfs deb server modify in `/etc/apt-cacher-ng/acng.conf` (arround line 372)
   ```
    PassThroughPattern: (packagecloud\.io|packagecloud-repositories\.s3\.dualstack\.us-west-1\.amazonaws\.com|packagecloud-prod\.global\.ssl\.fastly\.net):443$
   ```
- [x] automate `git-lfs` installation (see https://packagecloud.io/github/git-lfs/install)
    ```
    curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash
    sudo apt-get update
    sudo apt-get install git-lfs
    ```
- [x] add tmux config (see msh@cob4-2) done in https://github.com/ipa320/setup_cob4/pull/172
- [x] extend tmux config (see https://github.com/ipa320/setup_cob4/pull/172#issuecomment-337605560) see also #142; PR is #176 
- [ ] allow copy-paste from tmux: see [copy-paste-tmux](http://www.rushiagr.com/blog/2016/06/16/everything-you-need-to-know-about-tmux-copy-pasting-ubuntu/)
- [ ] configure default USB soundcard
   ```
   sudo vim /etc/modprobe.d/alsa-base.conf
   options snd-usb-audio index=0
   ```
   pay attention to `snd-usb-audio` that exists twice in the file - **change both**
   (also: don't forget to disable "Onboard Devises" Audio and Digital Microphone in BIOS!)

**Comment by ipa-fxm** [comment]
notes on extended tmux config can be found in #142

**Comment by ipa-fxm** [comment]
This issue was moved to mojin-robotics/setup_cob4#5
