### ISSUE TITLE
[paul-hamburg] apt-get upgrade broken due to kept back lts-kernel

### ISSUE THREAD

**Issue by ipa-fmw** [ipa320/setup_cob4#181]
installing git lfs on -b1 and -t1, t2, t3 works. doing the same on -s1 and -h1 fails during `sudo apt-get update`
```
W: Failed to fetch https://packagecloud.io/github/git-lfs/ubuntu/dists/trusty/main/source/Sources  Received HTTP code 403 from proxy after CONNECT
```

**Comment by ipa-fmw** [comment]
needed for https://github.com/ipa320/setup_cob4/issues/170

**Comment by ipa-fxm** [comment]
according to @ipa-fmw the `git-lfs`-steps worked for cob4-14-berlin
thus, this seems to be an individual issue of cob4-15-hamburg

**Comment by ipa-fmw** [comment]
not woth to investigate further as this is a paul-hamburg specific issue. robot works fine thus

**Comment by ipa-fxm** [comment]
it is worth an issue because currently sync script is broken!

**Comment by ipa-fxm** [comment]
solution used in #188 allowed to install `git-lfs` on paul-hamburg
however, sync_script is still broken due to 
```
robot@cob4-15-b1:~$ sudo apt-get upgrade 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
The following packages have been kept back:
  linux-generic-lts-xenial linux-headers-generic
  linux-headers-generic-lts-xenial linux-image-generic-lts-xenial
0 upgraded, 0 newly installed, 0 to remove and 4 not upgraded.
```

**Comment by ipa-fxm** [comment]
same on `cob4-12-h1`

**Comment by ipa-fxm** [comment]
maybe this helps (https://github.com/ipa320/setup_cob4/blob/master/images_config/ks-robot-master.cfg#L103):
`https://github.com/ipa-fmw/setup_cob4/blob/4e2bc5487e07f189d567cbbeb70e1958d9b126a7/images_config/ks-robot-master.cfg#L103`

**Comment by ipa-fmw** [comment]
somehow solves on cob4-12-h1. I could successfully run the sync script yesterday.

so this is a hamburg only issue

**Comment by ipa-fxm** [comment]
we set up the head pc from scratch...when reviving the robot last week
