### ISSUE TITLE
[test_rigs] enhance test rigs

### ISSUE THREAD

**Issue by floweisshardt** [ipa320/setup_cob4#202]
current test rigs are in https://github.com/ipa320/cob_hardware_test/tree/indigo_dev/cob_test_rigs (only FDM test rig)

we need extensions for
- [x] torso joint
- [x] head and sensorring joint
- [ ] arms
- [ ] grippers
- [ ] light_base
- [ ] light_torso
- [ ] bms
- [ ] laser scanners (front, left, right)
- [ ] flexisoft (wireless EM stop and fall sensors)
- [ ] audio in/out

**Comment by ipa-fxm** [comment]
there is also a single_schunk/elmo test setup with which any (arm, head, sensorring and torso) joint can be moved by specifying can bus and can id

**Comment by ipa-fxm** [comment]
we have torso, head and sensorring rigs up and running and documented

**Comment by fmessmer** [comment]
more suitable to be tracked in https://github.com/ipa320/cob_hardware_test/issues/20
