### ISSUE TITLE
candump tool

### ISSUE THREAD

**Issue by ipa-fmw** [ipa320/setup_cob4#48]
Folgende Schritte sind nun nötig zur Migration:
1. sudo initctl stop candump2mongodb
2. sudo rm /etc/init/candump2mongodb.conf
3. socket_buffer.py nach /usr/local/bin kopieren
4. sudo chmod +x  /usr/local/bin/socket_buffer.py
5. candump_any.conf nach /etc/init/ kopieren
6. sudo initctl start candump_any

Falls nötig kann ich da auch per Teamviewer unterstützen.

Die neue Lösung arbeitet etwas anders:
- Es werden per Voreinstellung die letzten  20000000 Zeilen (ca. 3 Stunden) candump im Speicher gehalten
- Die Daten gehen bei einem Neustart des NUCs verloren
- Auslesen über einen Socket: nc -U /tmp/candump_any.sock
- Die Daten werden rückwärts (neuste zuerst) ausgeben, das ermöglicht das Arbeiten mit | head
- mit tac kann man bei Bedarf auch wieder zurück sortieren, nach Möglichkeit aber offline

**Comment by ipa-fxm** [comment]
according to https://github.com/ipa320/cob4/issues/226#issuecomment-302147203 this can be setup/installed on every robot...

**Comment by ipa-fxm** [comment]
duplicate of #100?
has this been solved in #103?

**Comment by ipa-fmw** [comment]
solved in #103
