### ISSUE TITLE
cleanup start and stop scripts

### ISSUE THREAD

**Issue by ipa-fmw** [ipa320/setup_cob4#56]
this is how it should be

`cob-start-core`: 
  - checks for running `roscore` tmux session. if exists: do noting. if not exists: starts a new tmux session with roscore

`cob-stop-core`: 
  - 1st step: call `cob-stop`
  - 2nd step: terminate `roscore` tmux session and killall `roscore` and `rosmaster`

`cob-start`: 
  - 1st step: check for running `roscor and killall `roscore` and `rosmaster`e` tmux session. if no `roscore` exists: call `cob-start-core` if `roscore` exists: do nothing
  - 2nd step: check for running `bringup` tmux session. if no `bringup` exists: starts a new tmux session with bringup. if `bringup` exists: do nothing

`cob-stop`:
  -  terminate `bringup` tmux session (but keep `roscore` alive)

`cob-start-gui`: 
  - check if VM is running. if running: do nothing. if not running: start VM

`cob-stop-gui`: 
  - terminate VM

**Comment by ipa-mdl** [comment]
instead of using `rosnode cleanup` in `cob-stop` we could use something like
```python
#!/usr/bin/python
from rosnode import rosgraph, ID, rosnode_ping_all, cleanup_master_blacklist

pinged, unpinged = rosnode_ping_all()
if unpinged:
    master = rosgraph.Master(ID)
    cleanup_master_blacklist(master, unpinged)
```

It does the same, but non-interactively

**Comment by ipa-mdl** [comment]
Or simply `echo 'y' | rosnode cleanup`

**Comment by ipa-nhg** [comment]
Done https://github.com/ipa320/setup_cob4/pull/72/files

**Comment by ipa-fmw** [comment]
fixed in #72

**Comment by ipa-fmw** [comment]
please use solution from @ipa-mdl for cleanup (see https://github.com/ipa320/setup_cob4/issues/56#issuecomment-287436691)

**Comment by ipa-mdl** [comment]
The current solution with `echo 'y'` is fine, too!

**Comment by ipa-fmw** [comment]
doesn't this take longer (waiting for connection timeouts)? I thought your python version does get rod of that timeouts.

**Comment by ipa-mdl** [comment]
> doesn't this take longer (waiting for connection timeouts)? I thought your python version does get rod of that timeouts.

No, my version should just skips the [interactive confirmation](https://github.com/ros/ros_comm/blob/lunar-devel/tools/rosnode/src/rosnode/__init__.py#L462).

**Comment by ipa-fmw** [comment]
ok, then no need for change
