### ISSUE TITLE
Update install script and docu to use catkin build instead of catkin_make

### ISSUE THREAD

**Issue by ipa-nhg** [ipa320/setup_cob4#68]
@ipa-fxm @ipa-fmw @ipa-mdl should we meet and decide together the standard command lines to setup a new catkin (care-o-bot) workspace? 

The care-o-bot documentation and some Readme files had to be updated to follow the new instructions

**Comment by ipa-fxm** [comment]
we would need to adjust:
 - `catkin_init_workspace` (https://github.com/ipa320/setup_cob4/search?utf8=%E2%9C%93&q=catkin_init_workspace&type=)
 - `catkin_make` (https://github.com/ipa320/setup_cob4/search?utf8=%E2%9C%93&q=catkin_make&type=)

**Comment by ipa-fxm** [comment]
I guess we might want to use `catkin build --cmake-args -DCMAKE_BUILD_TYPE=Release`

See also http://catkin-tools.readthedocs.io/en/latest/verbs/catkin_build.html#full-command-line-interface

**Comment by ipa-fxm** [comment]
We should also add `python-catkin-tools` to the packages that are to be install by default on the robots and stud-PCs...

**Comment by ipa-fmw** [comment]
added it to the `care-o-bot-desktop` variant in https://github.com/ipa320/care-o-bot/pull/40

**Comment by ipa-fmw** [comment]
to check the catkin workspace we can no longer use `$ROS_PACKAGE_PATH` but use `$CMAKE_PREFIX_PATH`

please update docu where needed

**Comment by ipa-fxm** [comment]
#75 is related

**Comment by ipa-fxm** [comment]
Seems like we are still able to use both `catkin_make` and `catkin-tools` (see https://github.com/ipa320/setup_cob4/issues/75#issuecomment-299646684)

Thus, this is ticket here is nothing urgent but we sooner or later might want to switch...

**Comment by ipa-fxm** [comment]
`catkin_tools` is the tool of choice for quite a while now and used during:
- https://github.com/ipa320/setup_cob4/blob/master/PostInstallCob4.sh#L110
- https://github.com/unity-robotics/msh/blob/indigo_dev/setup_workspaces.sh#L26
