### ISSUE TITLE
why can't we use catkin build and catkin_make in parallel?

### ISSUE THREAD

**Issue by ipa-fmw** [ipa320/setup_cob4#75]
we had to make some changes to make our repos build with `catkin build`. Unfortunately after making that changes we're not able to compile with `catkin_make` any more. Seems to be relevant for all packages having `.so`-files checked in.
@ipa-mdl: any idea to make that compatible for both build tools?

**Comment by ipa-mdl** [comment]
`catkin-tools` is still not recommended.

**Comment by ipa-fmw** [comment]
but industrial-ci is using it, so we are somehow "forced" to switch to `catkin build`

**Comment by ipa-mdl** [comment]
Just for the tests ;)
Without context it's hard to tell what's wrong.
All packages that can be built with `catkin-tools` should be compilable with `catkin_make`, but not necessarily the other way.

**Comment by ipa-fmw** [comment]
@ipa-fxm: can you provide an example which compiles with `catkin build` but fails with `catkin_make`?

**Comment by ipa-fxm** [comment]
Well....I just tested this on my laptop with a fully loaded source space (bringup, simulation, navigation, perception, msh - all from source) and it compiles with `catkin_make` like a charm...
Also, we haven't really announced to use `catkin-tools` for compilation...so I guess there is still a bunch of people using `catkin_make`...and no one has compained or filed an issue...

Thus, I'll close this ticket... but I'd like to keep https://github.com/ipa320/setup_cob4/issues/68 open...sooner or later we might want to switch our scripts to use `catkin-tools`...or at least document the usage for **both** build tools
