### ISSUE TITLE
wrong configuration of apt-cacher (install script wrong?)

### ISSUE THREAD

**Issue by ipa-fmw** [ipa320/setup_cob4#77]
on e.g. cob4-7-t2 the /etc/apt/apt.conf.d/01proxy is
```
Acquire::http:Proxy "http://$server:3142";
```

but should be
```
Acquire::http:Proxy "http://cob4-7-b1:3142";
```

**Comment by ipa-fmw** [comment]
also base pc should be configured as apt-cacher client (-b1 is server and client at the same time)

**Comment by ipa-nhg** [comment]
This was solved on https://github.com/ipa320/setup_cob4/commit/e0be1f559af28c3e64376f8353e5bbb3a57b9ab6#diff-7c449be8b2d6c93045ec26632df86d7fR159
