### ISSUE TITLE
fix upstart installation (NHG:2)

### ISSUE THREAD

**Issue by ipa-fxm** [ipa320/setup_cob4#79]
after testing #61 today, `cob-start` and other "auto"-scripts did not work anymore

the assumption is that there might have been local, un-tracked changes/adjustments in the copied script files, i.e. **after** they have been copied to `/etc/init.d` using the `install_upstart.sh` script....
such changes should not be required to make the upstart scripts work!
(in case they still are required, at least, they should be made robot-independent and played back into `setup_cob4` as part of the PR)

in general, we should introduce a systematic testing procedure for changes/PRs within upstart scripts:
 - second person (with `sudo` right) checks out the respective feature branch
 - runs the `install_upstart.sh` afresh
 - turn off robot
 - turn on robot
 - then auto-bringup should be up and running

With this procedure, we make sure that not local changes need to be done in the **copied** files, but only in the **original** files from within `setup_cob4` (which is under version control)

@ipa-nhg 
Do you agree to this procedure?

might be related to #52

**Comment by ipa-nhg** [comment]
yes! the current problems are solved https://github.com/ipa320/setup_cob4/pull/80 , tested on cob4-9

**Comment by ipa-fxm** [comment]
I can confirm `upstart` to be working in `cob4-7`....
however, given our "new" review procedure, a second person is supposed to freshly run `upstart_install` @ipa-fmw 

however, it is not clear to me how the 4 PRs #80, #76, #61, #52 are to be sync'ed (they also seem to produce merge conflicts)...@ipa-nhg could you provide one PR which combines the three PRs and close the others?
#80 might be left aside as this is introducing something new...

**Comment by ipa-fxm** [comment]
upstart install fixed in #80
