### ISSUE TITLE
fix/sync apt-sources + setup cob4-7-s1 pc

### ISSUE THREAD

**Issue by ipa-fxm** [ipa320/setup_cob4#85]
followup of https://github.com/ipa320/setup_cob4/issues/81

the sync_package script was fixed in #84 
however, it revealed the following:
 - the apt sources configurations of the various `cob4-7` pcs differ - which they should not!
 - the `cob4-7-s1` pc probably needs to be set up afresh 
   - `/etc/apt/apt.conf.d/01proxy` is commented
   - seems to have some strange 32bit settings

**Comment by ipa-fmw** [comment]
new ps setup solved this issue
