### ISSUE TITLE
Update the upstart logic to check the cameras and boot the pcs

### ISSUE THREAD

**Issue by ipa-nhg** [ipa320/setup_cob4#89]
The current combination upstart+check_cameras can produce the following process:
ping cob4-X-t1 is once OK , but the check_camera script  (local on the cob4-Xt1) reboot again the pc because after 60 seconds detects an error with the asus. The upstart script goes to the next FOR loop(check if the file /tmp/check_done can be found) and return with an exception because cob4-X-t1 can not be reached, stoping the cob-start process

@ipa-fmw please correct me if I am wrong

**Comment by ipa-nhg** [comment]
@ipa-fmw @ipa-fxm the described above could not be your problem.
I wrote a small script to test it and if the pc where I check if the `/tmp/check_done` exists is not in my network ssh give me the  error `ssh: connect to host 10.4.7.50 port 22: No route to host` and the script continue executing the while loop until the file is found.

```
#!/bin/bash
while true; do
if ssh 10.4.7.50 stat /tmp/check_done \> /dev/null 2\>\&1
      then
         echo "File exists"
         Check_cam=True
         break
       else
         echo "File still does not exist"
fi
sleep 1
done

```

**Comment by ipa-nhg** [comment]
I removed the Timeout for the upstart_msh: https://github.com/ipa320/setup_cob4/pull/90 , this could be the problem if a non-camera pc needs more time than a camera pc to boot and tries to call robot.launch before all the pcs are booted. But I don't think this was your case if you waited 30 minutes...

**Comment by ipa-fxm** [comment]
ok....then let's close this and re-open in case it still appears....

**Comment by ipa-nhg** [comment]
I had the same issue today, I switched on the robot and upstart didn't start. If I reboot the base pc when all the other pcs are already there and the cameras found, upstart works. I will try to debug the error

 I only had this issue with paul-stuttgart..

**Comment by ipa-nhg** [comment]
I found an error on the local version on the robot, the cob-start installed was not checking the cameras the variable was defined as `camera_client_list `https://github.com/ipa320/setup_cob4/pull/92/commits/34d0962ec75091404e15f2c827ce52112ef7ab83#diff-95239c7f29eaaf264306bec7b3103af9R10 and loop use the variable `pc_cameras` https://github.com/ipa320/setup_cob4/pull/92/commits/34d0962ec75091404e15f2c827ce52112ef7ab83#diff-95239c7f29eaaf264306bec7b3103af9R32  that didn't exist.

**Comment by ipa-nhg** [comment]
Fixed with: https://github.com/ipa320/setup_cob4/pull/96/commits/0cdc5ec216915dd1a22555708b9490bc13d18031 

the command `ping -qc 1 -w 3 $i > /dev/null ` didn't return when the pc was not reached...

Testing and working on cob4-7!
